version: '3.8'
services:
  node_backend:
    container_name: node_backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    expose:
    - "3001"
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - postgres
  node_frontend:
    container_name: node_frontend_container
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment: 
    - NODE_ENV=production
    expose:
    - "3000"
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=QR_USER
      - POSTGRES_PASSWORD=alwaysLearning 
      - POSTGRES_DB=QR_DB
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
      - "5433:5433"
    volumes:
      - ./backend/src/config/createDatabaseSetup.sql:/docker-entrypoint-initdb.d/createDatabaseSetup.sql
